title: "Foro Digital 2027"
description: "Innovación, tecnología y colaboración"
locale: "es-ES"

url: "https://forodigital.github.io"
baseurl: "/forodigital2027"

remote_theme: "mmistakes/minimal-mistakes@4.28.0"

plugins:
  - jekyll-include-cache

# Skin base (luego lo convertimos a morado)
minimal_mistakes_skin: "default"
defaults:
  - scope:
      path: ""
    values:
      css: "/assets/css/custom.css"

# Navegación principal
nav:
  - title: "Acerca"
    url: /about/
  - title: "Sesiones"
    url: /sessions/
  - title: "Speakers"
    url: /speakers/
  - title: "Sponsors"
    url: /sponsors/
  - title: "Contacto"
    url: /contact/
sass:
  sass_dir: _sass
  style: compressed

include:
  - assets/css
