title: "Foro Digital 2027"
description: "Innovación, tecnología y colaboración"
baseurl: "/forodigital2027"
url: "https://forodigital.github.io"

theme: jekyll-theme-serif

markdown: kramdown
highlighter: rouge

collections:
  speakers:
    output: true
  sessions:
    output: true
  sponsors:
    output: true

sass:
  style: compressed
